/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.unn.piap_serverside.ui_modules;

import com.unn.piap_serverside.data_types.SCM;
import com.unn.piap_serverside.data_types.UI_ResourseCount;
import com.unn.piap_serverside.interfaces.SCMI;

/**
 *
 * @author STALKER
 */
public class UIM_DBS extends javax.swing.JPanel {
    private SCMI router = null;
    /**
     * Creates new form UIM_DBS
     */
    public UIM_DBS() {
        initComponents();
    }
    
    public void setRouter(SCMI router) {
        this.router = router;
    }
    
    public void updateStatusLabel(String status) {
        dbConnStateLabel.setText(status);
    }
    
    public void updateDbResourses(UI_ResourseCount rc) {
        numProectField.setText(Integer.toString(rc.numProect));
        numChairsField.setText(Integer.toString(rc.numChairs));
        numAuditField.setText(Integer.toString(rc.numAudit));
        numBoardField.setText(Integer.toString(rc.numBoard));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        connToDbBttn = new javax.swing.JButton();
        dbConnStateLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        numProectField = new javax.swing.JTextField();
        numChairsField = new javax.swing.JTextField();
        numAuditField = new javax.swing.JTextField();
        numBoardField = new javax.swing.JTextField();
        updateResBttn = new javax.swing.JButton();
        resetDbBttn = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        connToDbBttn.setText("Подключиться к БД");
        connToDbBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connToDbBttnActionPerformed(evt);
            }
        });

        dbConnStateLabel.setText("STATE");

        jLabel1.setText("Количество аудиторий");

        jLabel2.setText("Количество стульев");

        jLabel3.setText("Количество проекторов");

        jLabel4.setText("Количество досок");

        numProectField.setMinimumSize(new java.awt.Dimension(64, 64));

        numChairsField.setMinimumSize(new java.awt.Dimension(64, 64));

        numAuditField.setMinimumSize(new java.awt.Dimension(64, 64));

        numBoardField.setMinimumSize(new java.awt.Dimension(64, 64));

        updateResBttn.setText("Обновить ресурсы");
        updateResBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateResBttnActionPerformed(evt);
            }
        });

        resetDbBttn.setText("Обнулить БД");
        resetDbBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetDbBttnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(connToDbBttn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dbConnStateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(numBoardField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(updateResBttn))
                            .addComponent(numAuditField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numChairsField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numProectField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(resetDbBttn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(connToDbBttn)
                    .addComponent(dbConnStateLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(numAuditField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(numChairsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(numProectField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(numBoardField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateResBttn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resetDbBttn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void connToDbBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connToDbBttnActionPerformed
        SCM msg = SCM.nm()
                .setFrom(SCM.TID.UI_THREAD)
                .setTo(SCM.TID.DB_MANAGER_THREAD)
                .setType(SCM.TYPE.UIT_DB_CONNECT)
                .setBody(null);
        router.sendMessage(msg);
    }//GEN-LAST:event_connToDbBttnActionPerformed

    private void updateResBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateResBttnActionPerformed
        try {
            Integer numAudit = Integer.parseInt(numAuditField.getText());
            Integer numBoard = Integer.parseInt(numBoardField.getText());
            Integer numChairs = Integer.parseInt(numChairsField.getText());
            Integer numProect = Integer.parseInt(numProectField.getText());
            UI_ResourseCount ui_rc = new UI_ResourseCount(numAudit, numBoard, numChairs, numProect);
            SCM msg = SCM.nm()
                    .setFrom(SCM.TID.UI_THREAD)
                    .setTo(SCM.TID.DB_MANAGER_THREAD)
                    .setType(SCM.TYPE.UIT_DB_UPDATE_RESOURSES)
                    .setBody(ui_rc);
            router.sendMessage(msg);
        } catch(NumberFormatException ex) {
            
        }
    }//GEN-LAST:event_updateResBttnActionPerformed

    private void resetDbBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetDbBttnActionPerformed
        SCM msg = SCM.nm()
                .setFrom(SCM.TID.UI_THREAD)
                .setTo(SCM.TID.DB_MANAGER_THREAD)
                .setType(SCM.TYPE.UIT_DB_RESET)
                .setBody(null);
        router.sendMessage(msg);
    }//GEN-LAST:event_resetDbBttnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton connToDbBttn;
    private javax.swing.JLabel dbConnStateLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField numAuditField;
    private javax.swing.JTextField numBoardField;
    private javax.swing.JTextField numChairsField;
    private javax.swing.JTextField numProectField;
    private javax.swing.JButton resetDbBttn;
    private javax.swing.JButton updateResBttn;
    // End of variables declaration//GEN-END:variables
}
